# Cloud Build configuration for URL Shortener
steps:
  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/urlshortener-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/urlshortener-backend:latest'
      - './backend'
    id: 'build-backend'

  # Build frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/urlshortener-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/urlshortener-frontend:latest'
      - './frontend'
    id: 'build-frontend'

  # Push backend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/urlshortener-backend:$COMMIT_SHA'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push frontend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/urlshortener-frontend:$COMMIT_SHA'
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'urlshortener-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/urlshortener-backend:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--concurrency'
      - '100'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,PORT=8080'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,JWT_SECRET=JWT_SECRET:latest'
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'urlshortener-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/urlshortener-frontend:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '512Mi'
      - '--concurrency'
      - '100'
      - '--max-instances'
      - '5'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/urlshortener-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/urlshortener-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/urlshortener-backend:latest'
  - 'gcr.io/$PROJECT_ID/urlshortener-frontend:latest'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
  logging: 'CLOUD_LOGGING_ONLY'

# Timeout for the entire build
timeout: '1200s'